version: "3"
services:
  php_8:
    build: 
      ./php
    volumes: 
      - "./php:/var/www/html"
    ports:
      - "9000:9000"
  nginx:
    build:
      ./nginx
    ports:
      - "80:80"
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./php:/var/www/html"
    links:
      - php_8
  composer:
    image: composer
    command: composer install
    volumes:
      - "./php:/app"
