version: "3"
services:
  php_8:
    build: 
      ./php
    volumes: 
      - "./php:/var/www/html"
    ports:
      - "8000:8000"
    command: php -S 0.0.0.0:8000 -t /var/www/html

  composer:
    image: composer
    command: composer install
    volumes:
      - ".:/app"
